### ISSUE TITLE
[Bug]  `consistencyDisplay` is undefined in Inclusiveness page

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#115]
## Bug

In [Groundnud Niger Inclusiveness](https://leonarf.github.io/VCA4D/dist/study?id=groundnut-niger&currency=USD&view=inclusiveness), we have an error on the console

```
TypeError: e.studyData.ecoData.consistencyDisplay is undefined
```

And the Jobs part is not displayed.

**Comment by maximepiard** [comment]
@leonarf J'ai découvert ce bug: l'origine c'est qu'on a pas de fichier `eco.xlsx` pour cette étude (Groundnut Niger). 

Je pense que la bonne solution, c'est de supprimer le json et l'étude: On veut avoir toutes les données (ie l'excel) pour afficher correctement une étude.
A moinq que tu ai le fichier quelque part ?

**Comment by leonarf** [comment]
J'ai retrouvé le fichier xlsx sur mon PC et je l'ai mis dans le commit https://github.com/leonarf/VCA4D/commit/d86fef37ab561e12beb8bb2205f1bdfbf356f051 avec la mise à jour du fichier json

**Comment by maximepiard** [comment]
@leonarf Génial merci ! A priori on a le meme problème avec Groundnut-Ghana. Tu aurais aussi le fichier ?

**Comment by leonarf** [comment]
J'ai aussi ces fichiers. J'ai fait un commit dans main pour les ajouter, et mettre à jour les fichiers json associé

**Comment by maximepiard** [comment]
Merci @leonarf  !
