### ISSUE TITLE
S'adapter aux petits écrans

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#128]
https://www.notion.so/le-basic/S-adapter-aux-petits-crans-1056afc9ad64806aa235c5d6fccda172?pvs=4

## Contexte

Certaines informations n’apparaissent pas correctement sur les petits écrans

## Spec possibles

- Fixer une hauteur max pour la popup de comparaison, le sankey
- Autre ? Objectif min-hauteur = ❓
- ⚠️Attention, en zoomant, des éléments passent en dessous de la barre de footer, que se passe-t-il ?

![image](https://github.com/user-attachments/assets/ccc2aaa6-10ac-4b14-b98f-e80a32634dfd)

**Comment by leonarf** [comment]
On peut aussi fixer une largeur minimale en dessous de laquelle un scroll horizontal apparait. Car on n'a pas l'objectif d'afficher ce site sur des smartphones par exemple. Mais c'est vrai qu'il faudrait pas qu'il ne s'affiche bien que en plein écran sur un 22 pouces non plus ^^
