### ISSUE TITLE
[Page étude] Changer la devise

### ISSUE THREAD

**Issue by gaspardlebasic** [leonarf/VCA4D#58]
## Contexte
Actuellement il y a deux infos relatives à la devise : quelle est la monnaie locale du pays, et quelle devise est utilisée pour afficher les graphiques.
Je propose de fusionner ces deux infos.

### Affichage
- Le selecteur de devise s'affiche de [cette manière](https://www.figma.com/design/6mmWHxGGyAEAvgSUm5dGFD/VCA4D?node-id=132-195&t=8ij3GV4x8iB13gQs-1) :
![Capture d’écran 2024-07-31 à 17 11 31](https://github.com/user-attachments/assets/9f46682d-5919-478e-a8ca-2bebe7ab3ae3)

- Le libellé dans le dropdown est en toute lettres et correspond à la colonne libelle_devise_en de la table nomenclatures.devises (contrairement à aujourd'hui ou seules les abbréviations sont affichées)
- (si possible) Afficher quelle est la local currency dans le dropdown

### Comportement
- La valeur selectionnée par défaut est la devise locale
- Si je choisis une autre devise (euro ou dollar), le navigateur se souvient de mon choix
- Si je navigue alors vers une autre étude qui ne permet pas d'afficher les données dans la devise précédemment selectionnée, la devise locale est selectionnée par défaut

## Tests

**Comment by maximepiard** [comment]
@gaspardlebasic Que penses tu de ce résultat ? Tu peux tester sur `main-58`

| Avant | Après |
| - | - |
| [Screencast from 2024-08-19 17-07-51.webm](https://github.com/user-attachments/assets/4bc14b70-2b5f-4e61-bf13-84111406ccef) | [Screencast from 2024-08-19 17-08-15.webm](https://github.com/user-attachments/assets/f2b93add-2c7f-45b6-b173-68fa95a807bd)|

- J'ai laissé les symboles de devises, afin que les graphes plus loin soient compréhensibles ("What's a `millionBIF` :thinking: ")
- J'ai mis dans le sous-titre si c'était la devise locale ou une devise convertie. On _pourrait_ mettre l'année choisie pour le taux de conversion mais c'est un peu too much je pense ici
- j'ai mis un hover pour la découvrabilité du dropdown
- j'ai gardé "▼" au lieu de ton symbole sur Figma, faut de le trouver dans les caractères spéciaux. Qu'en penses tu ?

**Comment by gaspardlebasic** [comment]
Coucouuuu @maximepiard 

Tout me va dans ce que tu proposes :))))

Après test, je te reporte un bug :

1. Sur milk burundi j'ai choisi euro
2. J'ai ensuite navigué sur cashew ivory coast
3. La devise selectionnée dans la barre du haut est Euro (super) http://localhost:5173/study?id=cashew-ivory-coast&view=economic-growth
![Capture d’écran 2024-08-19 à 18 00 10](https://github.com/user-attachments/assets/a4d347c9-83de-4fbf-b58e-89cf4dbf5075)
4. La devise affichée dans le graphique de la page est Franc CFA (incohérent à priori)
![Capture d’écran 2024-08-19 à 18 00 17](https://github.com/user-attachments/assets/e0d6c7ed-0611-49c6-bd60-7db8bf61a415)

5. D'autre part mais j'imagine que ca n'a rien a voir, cette page est vide http://localhost:5173/study?id=cocoa-cameroon&currency=EUR

Bonne soirée !!!! A plus

**Comment by maximepiard** [comment]
@gaspardlebasic Merci !

- Je ne reproduis pas ce bug :thinking:, tu reproduis toujours ? Est ce que tu avais 2 fenetres d'ouvertes ?
- (5.) Bien vu :scream: ! Les études avec aucune données eco (pas de devise) crashaient :exploding_head: 
  - => Tu peux vérifier que c'est bon maintenant en mettant la branche a jour en local ? Merci !

**Comment by gaspardlebasic** [comment]
Yes je reproduis toujours. Une précision, c’est que pour retourner a la page d’accueil j’ai cliqué sur le titre « VCA4D information system » en haut a gauche. Sur Firefox, MacOS

Et sinon c’est tout bon pour l’etude cacao cameroun 😊

De : Maxime Piard ***@***.***>
Date : lundi, 19 août 2024 à 19:47
À : leonarf/VCA4D ***@***.***>
Cc : Gaspard Benoit ***@***.***>, Mention ***@***.***>
Objet : Re: [leonarf/VCA4D] [Page étude] Changer la devise (Issue #58)

@gaspardlebasic<https://github.com/gaspardlebasic> Merci !

  *   Je ne reproduis pas ce bug 🤔, tu reproduis toujours ? Est ce que tu avais 2 fenetres d'ouvertes ?
  *   (5.) Bien vu 😱 ! Les études avec aucune données eco (pas de devise) crashaient 🤯

     *   => Tu peux vérifier que c'est bon maintenant en mettant la branche a jour en local ? Merci !

**Comment by maximepiard** [comment]
@gaspardlebasic Est ce que tu peux aussi tester en prod (https://leonarf.github.io/VCA4D/dist/) pour voir si c'est un souci autre que mes changements ? Je ne reproduis toujours pas sur Ubuntu Firefox.

Merci :pray:

**Comment by gaspardlebasic** [comment]
Dac ! La par exemple
1. j'ai cliqué sur https://leonarf.github.io/VCA4D/dist/study?id=milk-burundi&currency=LOCAL
2. changé la devise ce qui m'amène sur https://leonarf.github.io/VCA4D/dist/study?id=milk-burundi&currency=USD
3. cliqué sur contribution to growth ce qui m'amène à https://leonarf.github.io/VCA4D/dist/study?id=milk-burundi&view=economic-growth
4. Le graphique est en Billion BIF :D et le select en USD, l'url ne comporte pas de devise

**Comment by maximepiard** [comment]
@gaspardlebasic Comme vu ensemble, le problème se pose quand on clique sur les sections jaunes qui redirigent vers les différentes pages dans l'overview

![image](https://github.com/user-attachments/assets/36e54eb8-7621-4294-a737-8cdd054e58c5)

Est ce que tu peux double-check que le problème est reglé sur `main-58-bug` (cette branche n'inclue pas les modifs de selecteur de currency) ? Merci !

**Comment by gaspardlebasic** [comment]
ca marche c'est bon :)
