### ISSUE TITLE
Refonte des selecteur d'unité pour la partie ACV

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#62]
## Spec

On redesign les toggles qui permettent de changer de scope / d'unité dans la page environnement

Figma: https://www.figma.com/design/6mmWHxGGyAEAvgSUm5dGFD?node-id=53-214#894839970 

Screenshot
![image](https://github.com/user-attachments/assets/2f3d358e-5662-4559-8aa0-01c71ebb33ac)

**Comment by leonarf** [comment]
Très bonne initiative. Il y avait un commentaire d'Angel (de VCA4D) qui demandait à avoir des bouton (?) pour pouvoir mettre + d'explication sur ce choix d'unité. À voir si ça sera toujours utile après ce refactoring, et il faudra lui demander ce qu'il voudrait écrire pour imagine la meilleure manière de l'afficher.
