### ISSUE TITLE
Avoir des "vraies" tooltips sur les "?"

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#64]
# Contexte

Dans les pages d'études, on voit les html-tooltip s'afficher lentement quand on hover une balise grise avec un "?"

Il faut que le tooltips'affiche plus vite, et soit plus beau

# Spec

### 1. Utiliser un tooltip en html custom pour `InfoTitle`, afin de 

- Afficher directement en hover
- formatter joliment le texte, parfoi très long

### 2. Afficher le tooltip uniquement sur l'icone "?"

**Comment by leonarf** [comment]
Est-ce qu'il ne faudrait pas pouvoir cliquer sur le (?) pour afficher directement la tooltip? Bonne idée ou mauvaise idée? Facile à faire ou pas?

**Comment by maximepiard** [comment]
@leonarf ça doit etre aussi facile que le hover j'imagine. Le hover étant mieux "découvrable" par l'utilisateur, on préfère cette option avec Gaspard.
Si ce n'est pas possible, on affiche le tooltip sur click.
