### ISSUE TITLE
Ajouter des indicateurs à la page de comparaison

### ISSUE THREAD

**Issue by leonarf** [leonarf/VCA4D#67]
Dans la page de comparaison, il faudrait ajouter l'indicateur 'Benefit/Cost Ratio (%)', pour la filière globalement et cliquer la ligne pour faire apparaître le même indicateur mais par 'stage' de la filière.

Il faudrait aussi ajouter la possiblité de cliqué sur un indicateur social pour voir le score des sous-indicateur associé (actuelle on affiche les score pour les 5 grandes catégories, il faudrait pouvoir affiche les score des sous-question de ces 5 catégories en cliquant dessus).

En réalisant ce travail, il faudrait essayé de mutualiser le code qui calcul les indicateurs (vu qu'on les calcul à la fois pour la page de comparaison et les pages économique ou social des études) et rendre facilement réutilisable le code qui permet d'afficher des sous-indicateur lorsqu'on clique sur une ligne de la page de comparaison.

Car la liste des indicateurs à afficher dans la page de comparaison est suceptible d'être modifiée encore en septembre.

**Comment by maximepiard** [comment]
@gaspardlebasic Quand tu auras le temps (aujourd'hui ce serait top), est ce qu'on peut brainstorm 30min sur

- Le design des rangs extensibles dans la page de comparaison (j'ai déjà fait un truc, cf ci dessous)
  [Screencast from 2024-08-20 19-42-00.webm](https://github.com/user-attachments/assets/10aa50b3-1b4a-4582-92c7-e19f95eadab2)
- Le design de https://github.com/leonarf/VCA4D/issues/74

**Comment by maximepiard** [comment]
@gaspardlebasic J'avais zappé que tu était absent ajd.

- Je me suis débrouillé, je suis revenu a un fond gris pour ne pas clasher avec les indicateurs de couleur.
  - Tu peux tester sur prod. Qu'en dis tu ?
  - J'ai aussi essayé de mettre des bordures au dropdown mais avec la structure html en `table` c'était pas simple du tout, donc j'ai laché l'affaire.
- Parlons en demain si ça te va :blush:

**Comment by gaspardlebasic** [comment]
Très cool tout ca ! Je te propose deux trucs de style :
- ajouter un poil de marge a gauche sur les rangées
- quand la rangée est développée, mettre le titre en gras
![Capture d’écran 2024-08-22 à 08 30 54](https://github.com/user-attachments/assets/af65d84d-8d92-4a86-8035-6511a30e3d6f)

Le tooltip je trouve ca super clair :))) Et en testant je suis tombé sur un étude avec les champs en majuscules comme ceci :
![Capture d’écran 2024-08-22 à 08 36 26](https://github.com/user-attachments/assets/eae083ae-8538-4c2c-9871-2a6a147a235f)
Avec du coup aussi la petite fleche qui est partie se balader en haut.

**Comment by maximepiard** [comment]
@gaspardlebasic Merci !

- J'imagine que c'est pour équilibrer les marges des 2 côtés ? Car elles sont déjà les mêmes. C'est juste qu'avec les badges "sociaux" on a un peu de marge a droite. Par exemple sur le dropdown `Benefit/Cost ratio`, la marge est équilibrée
  ![image](https://github.com/user-attachments/assets/1b33f01a-a668-4ba8-b0dc-b8894e02b2ab)
  
  Dis moi si tu veux vraiment une marge plus grosse a gauche, je ne suis pas sur que ce soit la solution mais tu me dis :grin: 
- C'est un bug, et quand tu refresh les majuscules ont disparues :thinking: 
  Après investigation c'est dû à du CSS tailwind :angry: . C'est réglé sur `main-74`. Ok pour toi ?
