### ISSUE TITLE
Retravailler le Sankey (à définir/affiné)

### ISSUE THREAD

**Issue by leonarf** [leonarf/VCA4D#68]
## Choix de l'unité

cf https://github.com/leonarf/VCA4D/issues/82#issuecomment-2304316570

![image](https://github.com/user-attachments/assets/36cccf4c-746a-4d70-a955-cd8e0d849946)

## Compréhension et arrangement du Sankey

_À définir_

**Comment by maximepiard** [comment]
Notes Gaspard 

- Couleur stages non repertoriés
	- Une couleur pour End use & COnsumers
	- Gris pour le reste
- Légende avec toutes couleurs répertoriées (grouper les memes couleurs, cf Figma)
- Mettre a l'echelle les flux (eg. burkina mango)
- Formattage tooltip, que faire ?
- Remove algo depth par stages => algo pour maxDepth only.

**Comment by maximepiard** [comment]
Taches restantes

- Regarder si on peut eviter que les labels se chevauchents
- Tooltip: mettre les produit / nom en titre
- Remettre l'espace entre million et la currency partout.
