### ISSUE TITLE
Popup de comparaison vide

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#75]
## Contexte

Lorsqu'on ouvre la popup de comparaison, la liste des etudes ne s'affiche pas

![image](https://github.com/user-attachments/assets/b456d49a-9adc-42d2-a46e-06069c44fea8)

**Comment by maximepiard** [comment]
@leonarf Je pense que ça vient du changement que tu as fait ici, https://github.com/leonarf/VCA4D/commit/f33b2a0671eb623a4a8f5e25a1ed07cf9d83945f

A cette ligne `studyData.id` est toujours `mango-guinea-bissau` (cette string est dans le json) et donc on ne trouve pas l'étude dans la liste de `data.json` avec `getStudy`.

A mon avis, il faudrait éviter de changer les noms / données des fichiers importés à la main, et toujours de baser sur le script d'import pour éviter ce genre de souci. On pourrait donc soit réimporter l'étude en changeant les noms dans les xls, soit seulement changer le `prettyName` dans data.json

Qu'en penses tu ? Je peux te laisser régler ce bug ?

**Comment by leonarf** [comment]
Merci pour la détection du bug. c'est corrigé.
