### ISSUE TITLE
Currency non affichée si on a une autre en local storage et que la currency n'est pas convertible

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#80]
## Bug

Ex Banana burundi

- Aller sur une autre étude
- Selectionner `Euro`
- Naviguer vers Banana burundi
- :bug: Le selecteur de monnaie est vide

![image](https://github.com/user-attachments/assets/30982ff3-9bc9-46ba-833c-ba575a769d62)

## Solution?

Charger la monnaie locale (et le mettre en lcoalStorage?) si on arrive sur une étude non convertible

**Comment by leonarf** [comment]
Oui pour la solution 
> Charger la monnaie locale (et la mettre en localStorage?) si on arrive sur une étude non convertible

En cherchant le fichier excel pour voir d'où venait le problème de monnaie pour cette étude, j'ai compris d'où ça venait et j'ai corrigé.
