### ISSUE TITLE
Trouver un meilleur picto que la balance pour la comparaison

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#81]
Depuis les pages d'études, mettre un logo avec 2 fleches (eg https://www.fnac.com/SearchResult/ResultList.aspx?Search=ordinateur&sft=1&sa=0) pour la comparaison

**Comment by maximepiard** [comment]
@gaspardlebasic Est ce que tu aurais a disposition un svg de double flech (comme sur la page de la fnac) 
![image](https://github.com/user-attachments/assets/1635e772-7237-4006-b3c0-3605ce5c8dad)

Ca pourrait ressembler à ce genre de nos picto 
![image](https://github.com/user-attachments/assets/082c7233-b6cd-4fa3-89d3-01dc354d56c4)

Sinon, tu as une bibliotheque libre de dispo pour ça ?

**Comment by leonarf** [comment]
Ou alors un symbol de yin yang?

**Comment by gaspardlebasic** [comment]
![BASIC_comparer](https://github.com/user-attachments/assets/e9c0a73c-5778-4e53-b960-7ab48c68f35b)

**Comment by maximepiard** [comment]
@gaspardlebasic Génial merci ! Est ce qu'on peut l'ajouter a la bibliotheque de pictos ?

**Comment by gaspardlebasic** [comment]
carrément ! tu parles de la bibliothèque sur le drive, dans le code ou sur figma ? sur le drive je l'ai mis, le code je vous laisse faire et Figma il faut que je regarde comment on fait

**Comment by maximepiard** [comment]
@gaspardlebasic Sur le drive :) 

Dans le code (du monorepo) on verra si on en a besoin, pour l'instant je n'ajoute qu'a VCA4D. Ca donne ça (en modifiant un poil les espacements) !

![image](https://github.com/user-attachments/assets/54a9e526-2504-4a1a-a8e5-c9d3a8e6d3e5)

**Comment by gaspardlebasic** [comment]
@maximepiard  gr888888
