### ISSUE TITLE
Rendre plus joli les boutons de téléchargement des fichiers Excel

### ISSUE THREAD

**Issue by leonarf** [leonarf/VCA4D#82]
Il y a des liens pour télécharger les fichiers excel à la fin de chaque page d'une étude.
Il faudrait les rendre + joli et + visible, peut-être les mettre ailleurs?
Travail de graphisme nécessaire.

**Comment by maximepiard** [comment]
@gaspardlebasic Une idée pour le design ici ?

Note que tous les liens de telechargements (Pdf et Xls) sont factorisés dans un composant. Dont un redesign les impacterais (de préférence) tous.

---

Aussi, je me demande si on pourrait pas refacto un peu le `Switch unit` du Sankey dans la page d'overview, qui n'est pas du tout au meme endroit que l'affichage de l'unité
[Screencast from 2024-08-22 11-58-19.webm](https://github.com/user-attachments/assets/5a93ce7f-f0c4-461f-8454-c530d577a3ce)

**Comment by gaspardlebasic** [comment]
@leonarf @maximepiard que pensez vous de ça ?
![Capture d’écran 2024-08-22 à 12 18 10](https://github.com/user-attachments/assets/1ac6c126-16bf-42e2-bc29-0e39779ad493)

**Comment by maximepiard** [comment]
@gaspardlebasic Il y a en effet de la place au niveau du menu, mais je ne suis pas sur que ça soit le bon endroit ou le bon display.

- Je pense que ça devrait etre plus discret sur la page. On veut que l'utilisateur.ice télécharge _pour aller plus loin_, et pas l'embrouiller avec trop d'informations lorsqu'il arrive sur une étude. A ce moment, la priorité est qu'iel découvre les graphiques et l'analayse en surface de l'étude.
- [détail] Outre l'emplacement Je trouve ça bizarre d'avoir des liens de telechargements qui ressemblent (par style et layout) a des liens de navigation.

Qu'en penses tu ?

**Comment by gaspardlebasic** [comment]
Et @maximepiard  pour l'unité du diagramme de flux je te propose ça :
![Capture d’écran 2024-08-22 à 12 26 16](https://github.com/user-attachments/assets/6d721271-2b57-42fb-9a68-824df87a39a3)
Avec le titre en h2 plutot que h3

**Comment by maximepiard** [comment]
@gaspardlebasic Parfaite utilisation de l'existant :ok_hand: Merci !

**Comment by gaspardlebasic** [comment]
> @gaspardlebasic Il y a en effet de la place au niveau du menu, mais je ne suis pas sur que ça soit le bon endroit ou le bon display.
> 
>     * Je pense que ça devrait etre plus discret sur la page. On veut que l'utilisateur.ice télécharge _pour aller plus loin_, et pas l'embrouiller avec trop d'informations lorsqu'il arrive sur une étude. A ce moment, la priorité est qu'iel découvre les graphiques et l'analayse en surface de l'étude.
> 
>     * [détail] Outre l'emplacement Je trouve ça bizarre d'avoir des liens de telechargements qui ressemblent (par style et layout) a des liens de navigation.
> 
> 
> Qu'en penses tu ?

Et comme ca ?
![Capture d’écran 2024-08-22 à 12 32 21](https://github.com/user-attachments/assets/caf726b1-7d04-491b-b851-acf2ee9dc2b7)
Une raison qui pourrait nous pousser a quand meme mettre ce contenu en haut est qu'un des types d'utilisateurices ciblées par ce site sont les chercheureuses

**Comment by leonarf** [comment]
> @gaspardlebasic Une idée pour le design ici ?
> 
> Note que tous les liens de telechargements (Pdf et Xls) sont factorisés dans un composant. Dont un redesign les impacterais (de préférence) tous.
> 
> Aussi, je me demande si on pourrait pas refacto un peu le `Switch unit` du Sankey dans la page d'overview, qui n'est pas du tout au meme endroit que l'affichage de l'unité [Screencast from 2024-08-22 11-58-19.webm](https://github.com/user-attachments/assets/5a93ce7f-f0c4-461f-8454-c530d577a3ce)

Pour le sankey, il faut qu'on le retravaille dans son ensemble, donc je pense qu'il vaut mieux voir le bouton de switch d'unit à ce moment là (s'il a toujours un sens et qu'on le garde)

**Comment by leonarf** [comment]
> > @gaspardlebasic Il y a en effet de la place au niveau du menu, mais je ne suis pas sur que ça soit le bon endroit ou le bon display.
> > ```
> > * Je pense que ça devrait etre plus discret sur la page. On veut que l'utilisateur.ice télécharge _pour aller plus loin_, et pas l'embrouiller avec trop d'informations lorsqu'il arrive sur une étude. A ce moment, la priorité est qu'iel découvre les graphiques et l'analayse en surface de l'étude.
> > 
> > * [détail] Outre l'emplacement Je trouve ça bizarre d'avoir des liens de telechargements qui ressemblent (par style et layout) a des liens de navigation.
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Qu'en penses tu ?
> 
> Et comme ca ? ![Capture d’écran 2024-08-22 à 12 32 21](https://private-user-images.githubusercontent.com/78796669/360394591-caf726b1-7d04-491b-b851-acf2ee9dc2b7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQzMjM1MDQsIm5iZiI6MTcyNDMyMzIwNCwicGF0aCI6Ii83ODc5NjY2OS8zNjAzOTQ1OTEtY2FmNzI2YjEtN2QwNC00OTFiLWI4NTEtYWNmMmVlOWRjMmI3LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODIyVDEwNDAwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTRhNGVkOWZhMjE4ZDhkMTU1MmY5OWI5NDk2YzE2OGUxOTQ5YWI0ZTczZDk3YjJjZGFlYjIxOWIzOTExYTQ5ODAmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.8VRaYvpZf5T1dqsisVnlO0Udbv5gmzYKwkc-0_P1_EY) Une raison qui pourrait nous pousser a quand meme mettre ce contenu en haut est qu'un des types d'utilisateurices ciblées par ce site sont les chercheureuses

Moi je préfèrerai vraiment qu'on mette des liens pour télécharger les documents aux endroits où c'est pertinent, et pas en première page aussi visible. Je propose de mettre le téléchargemet des données eco dans les 2 pages eco, les données environnement dans la page environnement, le pdf complet pas loin de l'affichage du pdf de 6 pages, et les données social dans la page social (sachant qu'il y a des chances que les clients souhaitent qu'on l'enlève quand ils le verront).

Pour rappel, rendre téléchargeable les fichiers excel, c'est pour répondre à leur demande de pouvoir télécharger les données sous forme de CSV. Car on n'a pas vraiment le temps de développer toute une interface pour générer des csv à la demande avec customisation des données et études dans le csv.
