### ISSUE TITLE
USD ne s'affiche pas quand une étude est en dollars de base

### ISSUE THREAD

**Issue by maximepiard** [leonarf/VCA4D#86]
## Contexte

Lorsqu'on va sur Cocoa ecuador alors que notre currency est réglé à USD, le selector est vide https://leonarf.github.io/VCA4D/dist/study?id=cocoa-ecuador&currency=USD&view=economic-growth

![image](https://github.com/user-attachments/assets/4048db2e-780a-474d-985c-3af3071ba3b8)

En effet, USD ici est `LOCAL`, mais l'option USD (convertie) n'existe pas.

## Solution(s) possible

- Rediriger vers `LOCAL` dans l'url
  - :heavy_check_mark: Simple
  - :x: Override le choix de l'utilisateur, qui verra les prochaines études en "Local" et pas en USD
- Afficher quand meme `USD` dans le selector dans ce cas
  - :heavy_check_mark: ne modifie pas le choix utilisateur
  - :x: Necessite de ne pas écrire "Converted from USD" en dessous dans ces cas précis (vaut aussi pour EUR)
- :question: Autre ?

**Comment by leonarf** [comment]
Je penche pour la 2nd options : `Afficher quand même USD dans le selector dans ce cas `.
Je dirai que le mieux serait de pouvoir comparer la currency LOCAL avec les currencies génériques (EUR et USD), et si la currency local est l'une des 2 génériques, réduire le nombre de choix proposé dans le selecteur de devises, et ne pas afficher "converted from ..." si ce n'est pas pertinent.
J'imagine que ça peut être faire dans le selecteur de divise directement, sans toucher à l'URL, mais je me trompe peut-être.
